--!nocheck

local MonsterBook = {
    SpikeFox = {
        Name = "Spike Fox",
        Icon = "rbxassetid://13886503379",
        IdleAnim = "SpikeWolfIdle",

        Drops = {
            SpikyFur = 80,
            SpikyQuills = 20
        }
    },
    SpikeWolf = {
        Name = "Spike Wolf",
        Icon = "rbxassetid://16483664838",
        IdleAnim = "SpikeWolfIdle",

        Drops = {
            SpikyFur = 70,
            SpikyQuills = 30
        }
    },
    ThornWolf = {
        Name = "Thorn Wolf",
        Icon = "rbxassetid://16483664838",
        IdleAnim = "SpikeWolfIdle",

        Drops = {
            SpikyFur = 60,
            SpikyQuills = 40
        }
    },
    ElderWolf = {
        Name = "Elder Wolf",
        Icon = "rbxassetid://18857836675",
        IdleAnim = "SpikeWolfIdle",

        Drops = {
            ElderWolfFur = 60,
            ElderWolfQuills = 40
        }
    },
    HardmodeWolf = {
        Name = "Hardmode Wolf",
        Icon = "rbxassetid://15688333545",
        IdleAnim = "SpikeWolfIdle",
        --// V0.9: BadgeId = 2212542348620168,
        BadgeId = 3730879662265300,

        Drops = {
            BlackFur = 90,
            BlackwolfNecklace = 10
        }
    },


    Kitsune = {
        Name = "Kitsune",
        Icon = "rbxassetid://17543155124",
        IdleAnim = "SpikeWolfIdle",

        Drops = {
            KitsuneFur = 60,
            KitsuneFlame = 40
        }
    },
    Stalker = {
        Name = "Stalker",
        Icon = "rbxassetid://17543156640",
        IdleAnim = "None",
        --// V0.9: BadgeId = 3246343070171491,

        Drops = {
            StalkerLeaf = 60,
            StalkerLog = 40,
        }
    },
    FrozenStalker = {
        Name = "Frozen Stalker",
        Icon = "",
        IdleAnim = "None",

        Drops = {
            StalkerLeaf = 60,
            StalkerLog = 40,
        }
    },

    GreenSlime = {
        Name = "Green Slime",
        Icon = "rbxassetid://15951815518",
        IdleAnim = "SlimeIdle",

        Drops = {
            SlimeGel = 80,
            SlimeCore = 20
        }
    },
    BlueSlime = {
        Name = "Blue Slime",
        Icon = "",
        IdleAnim = "SlimeIdle",

        Drops = {
            SlimeGel = 70,
            HealthPotion = 30
        }
    },
    LapisSlime = {
        Name = "Lapis Slime",
        Icon = "",
        IdleAnim = "SlimeIdle",

        Drops = {
            SlimeGel = 60,
            HealthPotion = 40
        }
    },
    PurpleSlime = {
        Name = "Purple Slime",
        Icon = "rbxassetid://18859513334",
        IdleAnim = "SlimeIdle",

        Drops = {
            SlimeGel = 50,
            MagicPotion = 50
        }
    },
    CrimsonSlime = {
        Name = "Crimson Slime",
        Icon = "rbxassetid://17543155439",
        IdleAnim = "SlimeIdle",
        --// V0.9: BadgeId = 2422984775435251,
        BadgeId = 3235712599678594,

        Drops = {
            CrimsonSlimeCore = 90,
            CrimsonSlimeFang = 10
        }
    },
    IceSlime = {
        Name = "Ice Slime",
        Icon = "",
        IdleAnim = "SlimeIdle",

        Drops = {
            IceSlimeCore = 50,
            IceCandy = 50
        }
    },
    SkyboundSlime = {
        Name = "Skybound Slime",
        Icon = "rbxassetid://18831198702",
        IdleAnim = "SlimeIdle",
        BadgeId = 1686200209412673,

        Drops = {
            SlimeGel = 50,
            SlimeCore = 50
        }
    }
}

return MonsterBook
