--!nocheck

local MonsterBook = {
    SpikeFox = {
        Name = "Spike Fox",
        Icon = "rbxassetid://13886503379",
        IdleAnim = "SpikeWolfIdle",

        Drops = {
            SpikyFur = 80,
            SpikyQuills = 20
        }
    },
    SpikeWolf = {
        Name = "Spike Wolf",
        Icon = "rbxassetid://16483664838",
        IdleAnim = "SpikeWolfIdle",

        Drops = {
            SpikyFur = 70,
            SpikyQuills = 30
        }
    },
    ThornWolf = {
        Name = "Thorn Wolf",
        Icon = "rbxassetid://16483664838",
        IdleAnim = "SpikeWolfIdle",

        Drops = {
            SpikyFur = 60,
            SpikyQuills = 40
        }
    },
    HardmodeWolf = {
        Name = "Hardmode Wolf",
        Icon = "rbxassetid://15688333545",
        IdleAnim = "SpikeWolfIdle",
        BadgeId = 2212542348620168,

        Drops = {
            BlackFur = 90,
            BlackwolfNecklace = 10
        }
    },

    Kitsune = {
        Name = "Kitsune",
        Icon = "rbxassetid://17543155124",
        IdleAnim = "SpikeWolfIdle",

        Drops = {
            KitsuneFur = 60,
            KitsuneFlame = 40
        }
    },
    Stalker = {
        Name = "Stalker",
        Icon = "rbxassetid://17543156640",
        IdleAnim = "None",
        BadgeId = 3246343070171491,

        Drops = {
            StalkerLeaf = 60,
            StalkerLog = 40,
        }
    },

    GreenSlime = {
        Name = "Green Slime",
        Icon = "rbxassetid://15951815518",
        IdleAnim = "SlimeIdle",

        Drops = {
            SlimeGel = 80,
            SlimeCore = 20
        }
    },
    BlueSlime = {
        Name = "Blue Slime",
        Icon = "rbxassetid://16483649460",
        IdleAnim = "SlimeIdle",

        Drops = {
            SlimeGel = 70,
            SlimeCore = 30
        }
    },
    LapisSlime = {
        Name = "Lapis Slime",
        Icon = "rbxassetid://16483649287",
        IdleAnim = "SlimeIdle",

        Drops = {
            SlimeGel = 60,
            SlimeCore = 40
        }
    },
    PurpleSlime = {
        Name = "Purple Slime",
        Icon = "rbxassetid://16483649160",
        IdleAnim = "SlimeIdle",

        Drops = {
            SlimeGel = 50,
            SlimeCore = 50
        }
    },
    CrimsonSlime = {
        Name = "Crimson Slime",
        Icon = "rbxassetid://17543155439",
        IdleAnim = "SlimeIdle",
        BadgeId = 2422984775435251,

        Drops = {
            CrimsonSlimeCore = 90,
            CrimsonSlimeFang = 10
        }
    },
}

return MonsterBook
