--!nocheck

local Ranks = {}

Ranks.RankRoleInfo = {
    [2] = {
        Role = "CS Tester",
        ChatRole = "Tester",
        Color = "#70a1ff"
    },
    [3] = {
        Role = "CS Grand Tester",
        ChatRole = "Tester+",
        Color = "#1e90ff"
    },
    [4] = {
        Role = "CS Trello Contributor",
        ChatRole = "Trello",
        Color = "#5352ed"
    },
    [125] = {
        Role = "CS Contributor",
        ChatRole = "Contributor",
        Color = "#ff6b81"
    },
    [126] = {
        Role = "CS Moderator",
        ChatRole = "Mod",
        Color = "#ff4757"
    },
    [255] = {
        Role = "CS Founder",
        ChatRole = "Founder",
        Color = "#ffa502"
    },
}
Ranks.CustomRoleInfo = {
    ["68027875"] = {
        Role = "CW Founder",
        ChatRole = "CW Founder",
        Color = "#ffa502"
    },
    ["2040399306"] = {
        Role = "CSV Founder",
        ChatRole = "CSV Founder",
        Color = "#ffa502"
    },
    ["1097119343"] = {
        Role = "CV Founder",
        ChatRole = "CV Founder",
        Color = "#ffa502"
    },
    ["3563941913"] = {
        Role = "CO Founder",
        ChatRole = "CO Founder",
        Color = "#ffa502"
    },
    ["91364976"] = {
        Role = "CR Founder",
        ChatRole = "CR Founder",
        Color = "#ffa502"
    },

    ["517042349"] = {
        Role = "Abyss The Executor",
        ChatRole = "Abyss",
        Color = "#3742fa"
    },
    ["850971587"] = {
        Role = "Alchemist User",
        ChatRole = "Alchemist",
        Color = "#7bed9f"
    },
    ["596899926"] = {
        Role = "Mayor of Carrotopia",
        ChatRole = "Carrot",
        Color = "#ff7f50"
    },
    ["748297118"] = {
        Role = "Known Illegal Merchant",
        ChatRole = "Merchant",
        Color = "#fd79a8"
    },
    ["332773444"] = {
        Role = "Sigma Male",
        ChatRole = "Sigma",
        Color = "#74b9ff"
    },
    ["1196067403"] = {
        Role = "Tree Monster Fanatic",
        ChatRole = "Tree",
        Color = "#2ed573"
    },
    ["1210467492"] = {
        Role = "Thingamybob",
        ChatRole = "Snow",
        Color = "#fff"
    },
    ["1680347725"] = {
        Role = "Strategist",
        ChatRole = "Strategist",
        Color = "#fff"
    },
    ["1457659888"] = {
        Role = "Striker",
        ChatRole = "Striker",
        Color = "#f79f1f"
    },
    ["1312728712"] = {
        Role = "Raid Shadow Legend",
        ChatRole = "Raid Shadow",
        Color = "#fd79a8"
    },
    ["1094363213"] = {
        Role = "Ebalo",
        ChatRole = "Ebalo",
        Color = "#e056fd"
    },
    ["232313396"] = {
        Role = "Mia",
        ChatRole = "Mia",
        Color = "#fd79a8"
    }
}

return Ranks
