
local RecipeBook = {}

RecipeBook.CraftingRecipes = {
    StalkerCape = {
        StalkerLeaf = 50,
        StalkerLog = 20,
        KitsuneFur = 10
    }
}

RecipeBook.ClassRecipes = {
    Warrior = {
        WarriorSlash = {
            SlimeGel = 30,
            SlimeCore = 10
        },
        WarriorDash = {
            SlimeGel = 30,
            KitsuneFur = 10
        },
        Excalibur = {
            SpikyQuills = 30
        }
    }
}

return RecipeBook
