--!nocheck
--!optimize 2
--!native

return {
    --- Stats
    ATKDMG = 0,
    TP = 0,
    Shield = 0,
    MaxShield = 5,
    OrbSpawnTime = 3,

    --- States
    InCombat = false,

    --- Buffes
    HealthBuff = 0,
    JumpBuff = 0,
    ATKDMGBuff = 0,
    ShieldBuff = 0,
    SpeedBuff = 0,
    RestoreBuff = 10,
    HealBuff = 10,

    BurnChance = 0,
    DodgeChance = 0,
    CriChance = 1,
    CriDMG = 100,

    --- Class stats
    Combo = 0,
    Arrows = 0,
    WizardCasted = 0,
    Guard = 0,
    RogueCritical = 0
}
