--!nocheck

return {
	Slot1 = {
		Stats = {
			Levels = 1,
			EXP = 0,
			Gold = 0,
			RP = 0,
			PlayTime = 0,

			Class = "Warrior",
			LastSeenLocation = "MonolithVillage",
			RespawnLocation = { "Vector3", 0, 0, 0 },

			LvPoints = 0,
			DmgPoints = 0,
			MagicPoints = 0,
			ManaPoints = 0,
			ShieldPoints = 0,
			HealthPoints = 0
		},

		QuestsV2 = {
			Main = 1,
			Town = {}
		},

		Settings = {
			Musics = true,
			SFXs = true,
			PotatoMode = false,
			PlayerList = true,
			MapDetails = true,
			CombatMode = "Solo"
		},

		Inventory = {},
	},
	Slot2 = {
		Stats = {
			Levels = 1,
			EXP = 0,
			Gold = 0,
			RP = 0,
			PlayTime = 0,

			Class = "Warrior",
			LastSeenLocation = "MonolithVillage",
			RespawnLocation = { "Vector3", 0, 0, 0 },

			LvPoints = 0,
			DmgPoints = 0,
			MagicPoints = 0,
			ManaPoints = 0,
			ShieldPoints = 0,
			HealthPoints = 0
		},

		QuestsV2 = {
			Main = 1,
			Town = {}
		},

		Settings = {
			Musics = true,
			SFXs = true,
			PotatoMode = false,
			PlayerList = true,
			MapDetails = true,
			CombatMode = "Solo"
		},

		Inventory = {},
	},
	Slot3 = {
		Stats = {
			Levels = 1,
			EXP = 0,
			Gold = 0,
			RP = 0,
			PlayTime = 0,

			Class = "Warrior",
			LastSeenLocation = "MonolithVillage",
			RespawnLocation = { "Vector3", 0, 0, 0 },

			LvPoints = 0,
			DmgPoints = 0,
			MagicPoints = 0,
			ManaPoints = 0,
			ShieldPoints = 0,
			HealthPoints = 0
		},

		QuestsV2 = {
			Main = 1,
			Town = {}
		},

		Settings = {
			Musics = true,
			SFXs = true,
			PotatoMode = false,
			PlayerList = true,
			MapDetails = true,
			CombatMode = "Solo"
		},

		Inventory = {},
	}
}
